export const PREDEFINED_ROLES = [
  "Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Machine Learning / AI Engineer",
  "Data Scientist",
  "Data Engineer",
  "DevOps / Platform Engineer",
  "Site Reliability Engineer (SRE)",
  "Mobile Engineer",
  "Product Manager",
  "UI/UX Designer",
  "Security Engineer",
  "QA / SDET",
  "Solutions Engineer",
  "Technical Program Manager",
  "Research Engineer",
  "Internship (Any Role)",
]

export const PREDEFINED_LOCATIONS = [
  "Remote (Worldwide)",
  "Remote (India)",
  "Bangalore",
  "Mumbai",
  "Delhi / NCR",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Noida / Gurgaon",
  "San Francisco Bay Area",
  "New York",
  "London",
  "Singapore",
  "Open to relocation",
]
